manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 3.5
      import: app/west.yml
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: 3.5
  self:
    path: .
