on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.5
    with:
      build_matrix_path: "config/build.yaml"
      config_path: "config"
